### ISSUE TITLE
CONTRIBUTING.md not found

### ISSUE THREAD

**Issue by roey-angel** [caporaso-lab/mockrobiota#79]
I'd like to contribute a new mock community but the link [http://mockrobiota.caporasolab.us/CONTRIBUTING.md](http://mockrobiota.caporasolab.us/CONTRIBUTING.md) isn't working.

**Comment by nbokulich** [comment]
Thanks @roey-angel for bringing this to my attention, and thanks for your interest in contributing! You can find the contributing guidelines here: https://github.com/caporaso-lab/mockrobiota/blob/master/CONTRIBUTING.md

Looks like the issue is that the contributing guidelines link is written as a relative link in the github readme, so this needs to be changed to an absolute link for the project page.
