### ISSUE TITLE
How can I distinguish those three mock communities from Mock-10 data?

### ISSUE THREAD

**Issue by chunyuma** [caporaso-lab/mockrobiota#93]
Hello,

I want to use [Mock-10 ](https://github.com/caporaso-lab/mockrobiota/tree/master/data/mock-10) data which has three mock communities. However, after I downloaded the fastq data based on the link provided in [dataset-metadata.tsv](https://github.com/caporaso-lab/mockrobiota/blob/master/data/mock-10/dataset-metadata.tsv), I don't know how to identify which mock community a read sequence belongs to. Perhaps I might run the following python command line provided in the [README.md](https://github.com/caporaso-lab/mockrobiota/blob/master/data/mock-10/README.md):

```
split_libraries_fastq.py -i mock-forward-read.fastq.gz -o split_libraries -m sample-metadata.tsv -b mock-index-read.fastq.gz --rev_comp_mapping_barcodes
```

However, this script might come from QIIME1 but now QIME has version2 and the version2 QIME seems not to provide this script. Also, I tried to run this command line by the script provided [here](https://github.com/biocore/qiime/blob/master/scripts/split_libraries_fastq.py) but it doesn't work.

Could you please give me some instructions about how I can know which mock community a read belongs to?

Thanks you!

**Comment by nbokulich** [comment]
Hi @chunyuma ,
I believe QIIME 1 is still installable as a virtualbox — otherwise the QIIME 2 action `qiime demux emp-single` would be the equivalent command. You can see the QIIME 2 documentation for usage instructions, and please see the QIIME 2 forum if you run into issues using that command. Eventually I plan to update the usage instructions for mockrobiota to use QIIME 2 — but in theory any demultiplexing method should work.

There is an example on the QIIME 2 forum of how to use mockrobiota data in an example analysis, but it uses mock-25, which does not need to be demultiplexed — nevertheless, this might help: https://forum.qiime2.org/t/fungal-its-analysis-tutorial/7351

Good luck!

**Comment by chunyuma** [comment]
Thanks @nbokulich!
